name: RR_to_RMS_customerdata
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # 毎時0分

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: python scripts/RR_to_RMS_customerdata.py
        env:
          RAKURAKU_TOKEN: ${{ secrets.RAKURAKU_TOKEN }}
          RMS_SERVICE_SECRET: ${{ secrets.RMS_SERVICE_SECRET }}
          RMS_LICENSE_KEY: ${{ secrets.RMS_LICENSE_KEY }}