name: RR_to_RMS_customerdata
on:
  schedule:
    - cron: '0 * * * *'  # 毎時0分

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: python scripts/RR_to_RMS_customerdata.py
        env:
          RMS_API_KEY: ${{ secrets.RMS_API_KEY }}
          RAKURAKU_API_KEY: ${{ secrets.RAKURAKU_API_KEY }}