name: RR_to_SS_zenkokuseiyaku
on:
  schedule:
    - cron: '10 8 * * *'  # 毎日8時10分UTC

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - run: python scripts/RR_to_SS_zenkokuseiyaku.py
        env:
          RAKURAKU_TOKEN: ${{ secrets.RAKURAKU_TOKEN }}
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}